# This file was generated by GoReleaser. DO NOT EDIT.
class BastionPodCtl < Formula
  desc "A tool for creating tcp tunnels into a private network via a Pod running on a kubernetes worker node in that private network"
  homepage "https://github.com/norwoodj/bastion-pod-ctl"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/norwoodj/bastion-pod-ctl/releases/download/v0.1.0/bastion-pod-ctl_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "f71bee44a5d7a99eb8a0533a986c344a0e50e659cdfa9dd4cd3d147e4ac2fbe8"
  elsif OS.linux?
    url "https://github.com/norwoodj/bastion-pod-ctl/releases/download/v0.1.0/bastion-pod-ctl_0.1.0_Linux_x86_64.tar.gz"
    sha256 "9ae7835f478e0fed29e099fac3fef20b4fd39fd8a85e743e664c2d3d378baa43"
  end

  def install
    bin.install "bastion-pod-ctl"
  end

  test do
    system "#{bin}/bastion-pod-ctl --version"
  end
end
