# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmDocs < Formula
  desc "Automatically generate markdown documentation for helm charts"
  homepage "https://github.com/norwoodj/helm-docs"
  version "1.14.0"

  on_macos do
    on_intel do
      url "https://github.com/norwoodj/helm-docs/releases/download/v1.14.0/helm-docs_1.14.0_Darwin_x86_64.tar.gz"
      sha256 "d65d0f2b13389ed5a2119d83735fc242cce16c7d35a394dcc19b50426ecd05d1"

      def install
        bin.install "helm-docs"
      end
    end
    on_arm do
      url "https://github.com/norwoodj/helm-docs/releases/download/v1.14.0/helm-docs_1.14.0_Darwin_arm64.tar.gz"
      sha256 "5b684b64cd62bc474054c1c7700f64364af7e312a4a284f90ae5f272f1c023bf"

      def install
        bin.install "helm-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/norwoodj/helm-docs/releases/download/v1.14.0/helm-docs_1.14.0_Linux_x86_64.tar.gz"
        sha256 "a9a4461edfec8bdab76ddcf05fe1fb4221cf338e2bdd310db91dab6469131fcf"

        def install
          bin.install "helm-docs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/norwoodj/helm-docs/releases/download/v1.14.0/helm-docs_1.14.0_Linux_arm6.tar.gz"
        sha256 "8f7af94c38dcf5708e54094659b238b07068de5d5156624de01fe51b60588d6a"

        def install
          bin.install "helm-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/norwoodj/helm-docs/releases/download/v1.14.0/helm-docs_1.14.0_Linux_arm64.tar.gz"
        sha256 "6d775aad428bce90c72ee94ea35817e5d03bd923b0b2c5b899693f719224ae9b"

        def install
          bin.install "helm-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/helm-docs --version"
  end
end
