# This file was generated by GoReleaser. DO NOT EDIT.
class HelmDocs < Formula
  desc "Automatically generate markdown documentation for helm charts"
  homepage "https://github.com/norwoodj/helm-docs"
  version "0.4.0"

  if OS.mac?
    url "https://github.com/norwoodj/helm-docs/releases/download/v0.4.0/helm-docs_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "7d343eded35ae561da0ab080f0e2d3247d5deecb7bc5b1702a24083248a793cc"
  elsif OS.linux?
    url "https://github.com/norwoodj/helm-docs/releases/download/v0.4.0/helm-docs_0.4.0_Linux_x86_64.tar.gz"
    sha256 "5c37a4f09a62fb4d60752ec949e9be02b38766d44d2f6c110670ea48087771de"
  end

  def install
    bin.install "helm-docs"
  end

  test do
    system "#{bin}/helm-docs --version"
  end
end
